"use client"

import { StudioHeader } from "@/components/studio/StudioHeader"
import { ExportFormatBar } from "@/components/studio/ExportFormatBar"
import { StudioScreenshotGallery } from "@/components/studio/StudioScreenshotGallery"
import { StudioScreenshotModal } from "@/components/studio/StudioScreenshotModal"
import { HiddenCaptureSurfaces } from "@/components/studio/HiddenCaptureSurfaces"
import { HowToGuide } from "@/components/studio/HowToGuide"
import { CameraHero } from "@/components/studio/CameraHero"
import { useStudioSession } from "@/hooks/useStudioSession"

export default function CameraRecorder() {
  const {
    adjustLightIntensity,
    aspectRatio,
    cameraError,
    cancelScreenshotTimer,
    canvasRef,
    clearScreenshots,
    closeScreenshotModal,
    cropArea,
    cropCanvasRef,
    currentTime,
    downloadAllScreenshots,
    downloadOriginalVideo,
    downloadProgress,
    downloadScreenshot,
    downloadTrimmedVideo,
    effectCanvasRef,
    effectCropArea,
    effectIntensity,
    exportFormat,
    getVideoDisplayArea,
    handleCropMouseDown,
    handleEffectCropMouseDown,
    handlePanStart,
    handlePipMouseDown,
    isCapturingScreenshot,
    isCropMode,
    isDownloadingAll,
    isEffectCropMode,
    isFullscreen,
    isGeneratingThumbnails,
    isHDScreenshot,
    isLightMode,
    isMirrored,
    isMounted,
    isPanning,
    isPlaying,
    isScreenshotModalOpen,
    isTimerActive,
    lightIntensity,
    mp4RecordingSupported,
    navigateScreenshot,
    openScreenshotModal,
    panOffset,
    pipCanvasRef,
    pipPosition,
    previewEffectCanvasRef,
    processingProgress,
    recordingMode,
    recordingState,
    recordingTime,
    resetRecording,
    resetZoom,
    screenError,
    screenStream,
    screenVideoRef,
    screenshotCanvasRef,
    screenshotCount,
    screenshotFormat,
    screenshotTimer,
    screenshots,
    seekTo,
    selectedScreenshotIndex,
    setAspectRatio,
    setEffectIntensity,
    setExportFormat,
    setIsHDScreenshot,
    setRecordingState,
    setScreenshotFormat,
    setScreenshotTimer,
    setSelectedScreenshotIndex,
    setTrimEnd,
    setTrimStart,
    setVideoEffect,
    showFlash,
    startRecording,
    stopRecording,
    switchToPip,
    switchToScreen,
    switchToWebcam,
    takeScreenshot,
    thumbnails,
    timerCountdown,
    toggleCropMode,
    toggleEffectCropMode,
    toggleFullscreen,
    toggleLightMode,
    toggleMirror,
    togglePlayback,
    trimEnd,
    trimStart,
    videoContainerRef,
    videoDuration,
    videoEffect,
    videoRef,
    webCodecsSupported,
    zoomIn,
    zoomLevel,
    zoomOut,
  } = useStudioSession()

  return (
    <div className="studio-shell p-4 md:p-6 lg:p-8">
      <div className="max-w-6xl mx-auto space-y-6">
        <StudioHeader
          mp4RecordingSupported={mp4RecordingSupported}
          webCodecsSupported={webCodecsSupported}
          recordingMode={recordingMode}
          isCropMode={isCropMode}
          zoomLevel={zoomLevel}
          isMirrored={isMirrored}
          videoEffect={videoEffect}
          effectIntensity={effectIntensity}
          isEffectCropMode={isEffectCropMode}
          isLightMode={isLightMode}
          lightIntensity={lightIntensity}
          isHDScreenshot={isHDScreenshot}
          recordingState={recordingState}
          recordingTime={recordingTime}
        />
        <div className="w-full space-y-8 mt-8">
          <ExportFormatBar
            recordingState={recordingState}
            exportFormat={exportFormat}
            onExportFormatChange={setExportFormat}
            mp4RecordingSupported={mp4RecordingSupported}
            webCodecsSupported={webCodecsSupported}
          />
          <CameraHero
            stage={{
              adjustLightIntensity,
              aspectRatio,
              cameraError,
              cancelScreenshotTimer,
              cropArea,
              currentTime,
              downloadOriginalVideo,
              downloadTrimmedVideo,
              effectCropArea,
              effectIntensity,
              exportFormat,
              getVideoDisplayArea,
              handleCropMouseDown,
              handleEffectCropMouseDown,
              handlePanStart,
              handlePipMouseDown,
              isCapturingScreenshot,
              isCropMode,
              isEffectCropMode,
              isFullscreen,
              isGeneratingThumbnails,
              isHDScreenshot,
              isLightMode,
              isMirrored,
              isMounted,
              isPanning,
              isPlaying,
              isTimerActive,
              lightIntensity,
              mp4RecordingSupported,
              panOffset,
              pipPosition,
              previewEffectCanvasRef,
              processingProgress,
              recordingMode,
              recordingState,
              recordingTime,
              resetRecording,
              resetZoom,
              screenError,
              screenStream,
              screenVideoRef,
              screenshotFormat,
              screenshotTimer,
              seekTo,
              setAspectRatio,
              setEffectIntensity,
              setIsHDScreenshot,
              setRecordingState,
              setScreenshotFormat,
              setScreenshotTimer,
              setTrimEnd,
              setTrimStart,
              setVideoEffect,
              showFlash,
              startRecording,
              stopRecording,
              switchToPip,
              switchToScreen,
              switchToWebcam,
              takeScreenshot,
              thumbnails,
              timerCountdown,
              toggleCropMode,
              toggleEffectCropMode,
              toggleFullscreen,
              toggleLightMode,
              toggleMirror,
              togglePlayback,
              trimEnd,
              trimStart,
              videoContainerRef,
              videoDuration,
              videoEffect,
              videoRef,
              zoomIn,
              zoomLevel,
              zoomOut,
            }}
          />

          <StudioScreenshotGallery
            screenshots={screenshots}
            screenshotCount={screenshotCount}
            isDownloadingAll={isDownloadingAll}
            downloadProgress={downloadProgress}
            onDownloadAll={downloadAllScreenshots}
            onClearAll={clearScreenshots}
            onScreenshotClick={openScreenshotModal}
            onDownloadScreenshot={downloadScreenshot}
          />
          <StudioScreenshotModal
            isOpen={isScreenshotModalOpen}
            screenshots={screenshots}
            selectedScreenshotIndex={selectedScreenshotIndex}
            screenshotFormat={screenshotFormat}
            isMirrored={isMirrored}
            isCropMode={isCropMode}
            onClose={closeScreenshotModal}
            onNavigate={navigateScreenshot}
            onSelectIndex={setSelectedScreenshotIndex}
            onDownload={downloadScreenshot}
          />
          <HiddenCaptureSurfaces
            canvasRef={canvasRef}
            screenshotCanvasRef={screenshotCanvasRef}
            cropCanvasRef={cropCanvasRef}
            effectCanvasRef={effectCanvasRef}
            pipCanvasRef={pipCanvasRef}
            screenVideoRef={screenVideoRef}
          />
          <HowToGuide />
        </div>
      </div>
    </div>
  )
}
